### ISSUE TITLE
failed to compile on MacOSX 10.11 

### ISSUE THREAD

**Issue by anguskwan** [gosu/gosu#286]
no matter the command line versions is xcode 6/xcode 7... please help

```
[anguskwan:~]$ brew install sdl2 libogg libvorbis
Warning: sdl2-HEAD already installed
Warning: libogg-1.3.2 already installed
Warning: libvorbis-1.3.5 already installed

[anguskwan:~]$ gem install gosu
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
	ERROR: Failed to build gem native extension.

    /Users/anguskwan/.rvm/rubies/ruby-2.1.6/bin/ruby -r ./siteconf20150731-33562-1szkru.rb extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling gosu_wrap.cxx
gosu_wrap.cxx:5437:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
      ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                  ^
../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
        void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
             ^
1 warning generated.
compiling Audio-AudioOpenAL.cpp
In file included from Audio-AudioOpenAL.cpp:1:
In file included from ./../../src/Audio/AudioOpenAL.mm:1:
In file included from ./../../src/Audio/AudioOpenAL.cpp:1:
In file included from ./../../src/Audio/ALChannelManagement.hpp:5:
./../../src/Audio/../MacUtility.hpp:36:16: warning: 'GetMacOSStatusErrorString' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
            << GetMacOSStatusErrorString(status)
               ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Debugging.h:807:1: note: 'GetMacOSStatusErrorString' has been explicitly marked deprecated here
GetMacOSStatusErrorString(OSStatus err)                       __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_4, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
^
In file included from Audio-AudioOpenAL.cpp:1:
In file included from ./../../src/Audio/AudioOpenAL.mm:1:
In file included from ./../../src/Audio/AudioOpenAL.cpp:1:
In file included from ./../../src/Audio/ALChannelManagement.hpp:5:
./../../src/Audio/../MacUtility.hpp:37:24: warning: 'GetMacOSStatusCommentString' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
            << " (" << GetMacOSStatusCommentString(status) << ")";
                       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Debugging.h:848:1: note: 'GetMacOSStatusCommentString' has been explicitly marked deprecated here
GetMacOSStatusCommentString(OSStatus err)                     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_4, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
^
In file included from Audio-AudioOpenAL.cpp:1:
In file included from ./../../src/Audio/AudioOpenAL.mm:1:
In file included from ./../../src/Audio/AudioOpenAL.cpp:2:
./../../src/Audio/OggFile.hpp:6:10: fatal error: 'vorbis/vorbisfile.h' file not found
#include <vorbis/vorbisfile.h>
         ^
2 warnings and 1 error generated.
make: *** [Audio-AudioOpenAL.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/anguskwan/.rvm/gems/ruby-2.1.6/gems/gosu-0.9.2 for inspection.
Results logged to /Users/anguskwan/.rvm/gems/ruby-2.1.6/extensions/x86_64-darwin-14/2.1.0/gosu-0.9.2/gem_make.out

```

**Comment by jlnr** [comment]
RVM has caused nothing but trouble in the last years. Have you tried installing Gosu using system Ruby or `rbenv`? Does `/usr/local/include/vorbis/vorbisfile.h` exist?

**Comment by jlnr** [comment]
I have a 10.11 VM now, and Gosu is indeed broken. The ATSUI framework, long deprecated, has been removed. Will replace it ASAP.

**Comment by jlnr** [comment]
0.10.2 works with system Ruby on 10.11, will release later today

**Comment by petros** [comment]
What's the latest recommendation ruby-version-wise and gosu-version-wise for El capitan? I am trying to install the gem and can't make it work. I am using rbenv with Ruby 2.2.3 and trying to install gosu 0.10.2 and I get the following:

```
Installing gosu 0.10.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/boxen/rbenv/versions/2.2.3/bin/ruby -r ./siteconf20151108-5117-aru1ri.rb extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling stb_vorbis.c
compiling gosu_wrap.cxx
gosu_wrap.cxx:5455:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
      ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                  ^
../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
        void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
             ^
1 warning generated.
compiling Audio-Audio.cpp
compiling Bitmap-Bitmap.cpp
compiling Bitmap-BitmapIO.cpp
compiling DirectoriesUnix.cpp
compiling FileUnix.cpp
compiling Graphics-BlockAllocator.cpp
compiling Graphics-Color.cpp
compiling Graphics-Graphics.cpp
compiling Graphics-Image.cpp
compiling Graphics-LargeImageData.cpp
compiling Graphics-Macro.cpp
compiling Graphics-Resolution.cpp
In file included from Graphics-Resolution.cpp:1:
./../../src/Graphics/Resolution.cpp:49:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
         ^
1 error generated.
make: *** [Graphics-Resolution.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gosu-0.10.2 for inspection.
Results logged to /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.2/gem_make.out
```

**Comment by jlnr** [comment]
@petros Every Ruby > 1.8 should work with the current version of Gosu, actually. Have you run `brew install sdl2` before installing Gosu?

**Comment by petros** [comment]
> Have you run `brew install sdl2` before installing Gosu?

Yes, this is what I have installed currently:

```
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/bin/sdl2-config
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/include/SDL2/ (64 files)
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/lib/libSDL2-2.0.0.dylib
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/lib/pkgconfig/sdl2.pc
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/lib/ (4 other files)
/opt/boxen/homebrew/Cellar/sdl2/2.0.3/share/aclocal/sdl2.m4
```

Any chance the non-default homebrew installation messes things up?

**Comment by jlnr** [comment]
Ah, yes. Gosu should probably use `sdl2-config` on OS X, but right now the SDL 2 path is hardcoded to `/usr/local/include/SDL2`. I'll try to fix this later today - I have to release a hotfix for Windows, anyway.

**Comment by jlnr** [comment]
@petros I have released a preview gem that uses `sdl2-config`, can you please verify that it solves the issue for you? `gem install gosu -v 0.10.5.pre1`

**Comment by petros** [comment]
@jlnr yay! It installs now!

Unfortunately, when I try to run something that uses gosu, I see this:

```
$ ruby whack_a_ruby.rb
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': dlopen(/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle, 9): Symbol not found: _SDL_GameControllerClose (LoadError)
  Referenced from: /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle
  Expected in: flat namespace
 in /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle - /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gosu-0.10.5.pre1/lib/gosu.rb:16:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from whack_a_ruby.rb:9:in `<main>'
```

**Comment by jlnr** [comment]
Ouch, another embarrassing typo. I need a free weekend to hack on Gosu, all my late-night fixes are terrible :)

Please retry with: `gem install gosu -v 0.10.5.pre1`
(And excuse the confusing versioning scheme here, I have to work around a RubyGems bug right now =/)

**Comment by petros** [comment]
Same error I am afraid, thanks for taking the time to look into this though :smile: 

```
$ ruby whack_a_ruby.rb 
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': dlopen(/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle, 9): Symbol not found: _SDL_GameControllerClose (LoadError)
  Referenced from: /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle
  Expected in: flat namespace
 in /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle - /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/gosu-0.10.5.pre1/gosu.bundle
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gosu-0.10.5.pre1/lib/gosu.rb:16:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/boxen/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from whack_a_ruby.rb:9:in `<main>'
```

Also, what typo were you referring to? Just to be clear, I can install 0.10.5.pre1 without errors. It's running a ruby script that uses gosu what generates that error.

**Comment by jlnr** [comment]
It was a typo in `extconf.rb` that causes the dynamic linker error you are seeing: https://github.com/gosu/gosu/commit/f91c2865367f6b8d60b4889bf4585ca3e32d1648

And now there was another typo in my GitHub comment: I meant `gem install gosu -v 0.10.5.pre0`. Hence my comment regarding the versioning scheme - pre0 is new, pre1 is old.

**Comment by petros** [comment]
> I meant gem install gosu -v 0.10.5.pre0.

Oh man! I even tried 0.10.5.pre2, but didn't think of trying pre0. Sorry :smile: Let me try pre0 now

**Comment by petros** [comment]
Yes!!!! It works! Thanks so much! :smile:

**Comment by pmontu** [comment]
i am using macs stock ruby, and i have downloaded dependancies for gosu but i get the below error:

sudo gem install gosu -v 0.10.5.pre0
    Fetching: gosu-0.10.5.pre0.gem (100%)
    Building native extensions.  This could take a while...
    ERROR:  Error installing gosu:
    	ERROR: Failed to build gem native extension.

        /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
    The Gosu gem requires some libraries to be installed system-wide.
    See the following site for a list:
    https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

    creating Makefile

    make "DESTDIR="
    compiling stb_vorbis.c
    compiling gosu_wrap.cxx
    gosu_wrap.cxx:5444:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
          ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                      ^
    ../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
            void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
                 ^
    1 warning generated.
    gosu_wrap.cxx:5444:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
          ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                      ^
    ../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
            void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
                 ^
    1 warning generated.
    compiling Audio-Audio.cpp
    In file included from Audio-Audio.cpp:1:
    In file included from ./../../src/Audio/Audio.mm:1:
    In file included from ./../../src/Audio/Audio.cpp:1:
    In file included from ./../../src/Audio/ALChannelManagement.hpp:5:
    In file included from ./../../src/Audio/../AppleUtility.hpp:15:
    In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
    In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:6:
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
    @class NSArray<ObjectType>;
                  ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:16: error: cannot find protocol declaration for 'ObjectType'
    @class NSArray<ObjectType>;
                   ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:25: error: cannot find protocol declaration for 'ObjectType'
    @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                            ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:37: error: expected unqualified-id
    @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                                        ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:13: error: expected ')'
    - (nullable ObjectType)nextObject;
                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:3: note: to match this '('
    - (nullable ObjectType)nextObject;
      ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:25: error: cannot find protocol declaration for 'ObjectType'
    @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                            ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:1: error: duplicate interface definition for class 'NSEnumerator'
    @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:12: note: previous definition is here
    @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
               ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:37: error: method type specifier must start with '-' or '+'
    @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                        ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:38: error: expected a type
    @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                         ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: error: expected selector for Objective-C method
    @property (readonly, copy) NSArray<ObjectType> *allObjects;
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:36: error: cannot find protocol declaration for 'ObjectType'
    @property (readonly, copy) NSArray<ObjectType> *allObjects;
                                       ^
    In file included from Audio-Audio.cpp:1:
    In file included from ./../../src/Audio/Audio.mm:1:
    In file included from ./../../src/Audio/Audio.cpp:1:
    In file included from ./../../src/Audio/ALChannelManagement.hpp:5:
    In file included from ./../../src/Audio/../AppleUtility.hpp:15:
    In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:32: error: cannot find protocol declaration for 'ObjectType'
    @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                                   ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:44: error: expected unqualified-id
    @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                                               ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:19:4: error: expected a type
    - (ObjectType)objectAtIndex:(NSUInteger)index;
       ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:40: error: C++ requires a type specifier for all declarations
    - (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                     ~~~~~~^~~~~~~~~~
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:40: error: expected ')'
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:33: note: to match this '('
    - (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:20: error: cannot find protocol declaration for 'ObjectType'
    @interface NSArray<ObjectType> (NSExtendedArray)
                       ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:1: error: duplicate interface definition for class 'NSArray'
    @interface NSArray<ObjectType> (NSExtendedArray)
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
    @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
               ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
    @interface NSArray<ObjectType> (NSExtendedArray)
                                   ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [Audio-Audio.o] Error 1


    Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.5.pre0 for inspection.
    Results logged to /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.5.pre0/ext/gosu/gem_make.out

**Comment by jlnr** [comment]
@pmontu Yep, that looks like `gem` is using an outdated compiler. Have you maybe installed the Xcode Command Line Tools before upgrading OS X, and not updated them since?

**Comment by pmontu** [comment]
It works now, i removed xcode and installed/updated command line tools. Thank you for your reply @jlnr.

**Comment by matomatical** [comment]
Hi I'm having the same issue as @petros, installing gosu for the first time, but the preview versions that worked there are not working for me either.

I'm using system ruby on El Capitan, i've successfully run `brew install sdl2` and have just updated the command line tools.

here's what happens when i `sudo gem install gosu`

```
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
    ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

creating Makefile

make "DESTDIR="
compiling stb_vorbis.c
compiling gosu_wrap.cxx
gosu_wrap.cxx:5444:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
      ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                  ^
../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
        void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
             ^
1 warning generated.
gosu_wrap.cxx:5444:35: warning: 'drawRot' is deprecated [-Wdeprecated-declarations]
      ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                  ^
../../Gosu/Font.hpp:81:14: note: 'drawRot' has been explicitly marked deprecated here
        void drawRot(const std::wstring& text, double x, double y, ZPos z, double angle,
             ^
1 warning generated.
compiling Audio-Audio.cpp
compiling Bitmap-Bitmap.cpp
compiling Bitmap-BitmapIO.cpp
compiling DirectoriesUnix.cpp
compiling FileUnix.cpp
compiling Graphics-BlockAllocator.cpp
compiling Graphics-Color.cpp
compiling Graphics-Graphics.cpp
compiling Graphics-Image.cpp
compiling Graphics-LargeImageData.cpp
compiling Graphics-Macro.cpp
compiling Graphics-Resolution.cpp
In file included from Graphics-Resolution.cpp:1:
./../../src/Graphics/Resolution.cpp:49:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
         ^
1 error generated.
make: *** [Graphics-Resolution.o] Error 1


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.4 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.4/ext/gosu/gem_make.out
```

and here's the output from when i `sudo gem install gosu -v 0.10.5.pre0`, straight after

```
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
extconf.rb:98:in ``': No such file or directory - sdl2-config (Errno::ENOENT)
	from extconf.rb:98:in `<main>'


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.5.pre0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.5.pre0/ext/gosu/gem_make.out
```

any help appreciated!

**Comment by jlnr** [comment]
Hmm, have you added `/usr/local/bin` to your `$PATH`? You should have a tool called `sdl2-config` after installing SDL. Can you run `sdl2-config` in a Terminal? It should print some information on how to use it.

**Comment by matomatical** [comment]
Thank you for pointing me towards sld2-config.

I was getting `sdl2-config: command not found` so I tried reinstalling SDL2 via homebrew. This fixed everything, sdl2-config worked and gosu 0.10.4 has successfully installed. I got a Hello World window up and running :smiley_cat:

Thanks so much!

**Comment by jlnr** [comment]
:+1: Good to hear that re-installing SDL helped!
