### PR TITLE
Use macOS Sierra and macOS Mojave on Travis CI

### PR DESCRIPTION
**Pull request by pmer**
Now that Homebrew has updated to SDL2 2.0.10, SDL2 fails to build on OS X El Capitan with the error "use of undeclared identifier 'NSEventSubtypeMouseEvent'", which was introduced in macOS High Sierra. This is a regression introduced in SDL2 2.0.10 that will be fixed in
SDL2 2.0.11, but until that is released and added to Homebrew, Travis just going to build every build.

- Update "old Mac" Travis build to use macOS Sierra with the final release of Xcode 9, which is version 9.4.1.
- Update "new Mac" Travis build to use the latest Travis image, which is macOS Mojave with Xcode 11.0.
- Switch to using the Travis Homebrew addon, which should reduce macOS build times by several minutes.

See: https://travis-ci.org/gosu/gosu/jobs/583899519
See: https://travis-ci.org/gosu/gosu/jobs/583899520
See: https://discourse.libsdl.org/t/sdl-2-0-10-old-mac-os-el-capitan-10-11-and-xcode7-3/26554/4
See: https://hg.libsdl.org/SDL/rev/449d5819a84a
See: https://github.com/Homebrew/homebrew-core/pull/42619

### CODE REVIEW

**Comment by pmer** [comment]
As mentioned in https://discourse.libsdl.org/t/sdl-2-0-10-old-mac-os-el-capitan-10-11-and-xcode7-3/26554, you can build SDL2 2.0.10 on El Capitan as long as you have Xcode 8.3. Travis doesn't let you specify separate macOS and Xcode versions, though, so when we want to build with Xcode 8.3 we also get Sierra, as per Travis's `xcode8.3` image.

**Comment by pmer** [comment]
I wonder why Travis is failing to build here... I don't see an error in the build log...

**Comment by cyberarm** [comment]
@pmer The error was folded under `Installing Homebrew Packages` (for xcode 8.3)
```text
$ rvm $brew_ruby do brew bundle --verbose --global

/usr/local/bin/brew tap homebrew/bundle

==> Tapping homebrew/bundle

Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...

remote: Enumerating objects: 90, done.

remote: Counting objects: 100% (90/90), done.

remote: Compressing objects: 100% (80/80), done.

remote: Total 90 (delta 6), reused 29 (delta 4), pack-reused 0

Unpacking objects: 100% (90/90), done.

Tapped 0 formulae (185 files, 249.3KB)

Error: Your Homebrew is outdated. Please run `brew update`.

Error: Kernel.exit
```

**Comment by pmer** [comment]
Thanks! Good eyes.

**Comment by jlnr** [comment]
@pmer I've just received an email that Gosu can now use the [new GitHub Actions](https://github.com/features/actions). I'll look into it for some work projects and hopefully if it is easier to handle than Travis (not hard :)) we can look into setting it up for Gosu as well.
